Models/Recipe.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace e_cookbook.Models
{
    public class Recipe
    {

        public string Id { get; set; }
        public string Title { get; set; }
        public DateTime Createdat { get; set; }
        public DateTime Lastedit { get; set; }
        public string UserId { get; set; }
        
        
        public List<User> User { get; set; }
        public List<Comment> Comment { get; set; }
        public RecipeRating RecipeRating { get; set; }
        public List<RecipeStep> RecipeStep { get; set; }
        public List<RecipeIngredient> RecipeIngredients { get; set; }

       public List<Ingredient> Ingredients { get; set; }
      
    }
}

Controllers/RecipesController.cs
using System;
using System.Collections.Generic;
using System.Collections.Immutable;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using e_cookbook.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.EntityFrameworkCore;

namespace e_cookbook.Controllers
{
    public class RecipesController : Controller
    {
        private EcookbookContext _ecookbookContext;
        private UserManager<User> _userManager;
        private SignInManager<User> _signInManager;

        public RecipesController(EcookbookContext ecookbookContext, UserManager<User> userManager,
            SignInManager<User> signInManager)
        {
            _ecookbookContext = ecookbookContext;
            _userManager = userManager;
            _signInManager = signInManager;
        }

        [HttpGet]
        [Route("")]
        public async Task<IActionResult> Index()
        {
            
            if (!_ecookbookContext.Recipes.Any())
            {
                ViewBag.no_recipes = "Nie ma jeszcze żadnych przepisów";
            }
            else
            {
                var list = _ecookbookContext.Ingredients;
             //   var list2 = _ecookbookContext.RecipeIngredientses;
                                  
                var recipe_list = _ecookbookContext.Recipes.Select(c => new Recipe()
                {
                    Id = c.Id,
                    Title = c.Title,
                    Createdat = c.Createdat,
                    Lastedit = c.Lastedit,
                    Ingredients = null,
                    RecipeIngredients = (from i in _ecookbookContext.RecipeIngredientses where i.RecipeId == c.Id select i).ToList(),
                    RecipeStep = (from s in _ecookbookContext.RecipeSteps where s.RecipeId == c.Id select s).ToList()
                    
                }).ToList();
   
                ViewBag.recipes = recipe_list;
                
                
                foreach (var items  in  recipe_list)
                {
                    var cos = (from i in _ecookbookContext.RecipeIngredientses
                        where i.RecipeId == items.Id
                        select i.IngredientId).ToList();
                    items.Ingredients = _ecookbookContext.Ingredients.Where(s => cos.Contains(s.Id)).ToList();
                }
                //  ViewBag.ingredients = _ecookbookContext.Ingredients.ToList();
            }
            

            return View();
        }

        [Route("recipe/{id}")]
        public async Task<IActionResult> Recipe(string Id)
        {
            var id = new Guid(Id).ToString();
            var recipe = _ecookbookContext.Recipes.Where(Recipes => Recipes.Id == id).ToList();

            if (recipe.Count != 1)
            {
                ViewBag.noRecipe = "Brak przepisu o podanym ID";

                return View();
            }

            var comments = _ecookbookContext.Comments.Where(Comments => Comments.Recipe.Id == id).ToList();


            var stepList = new List<string>();
            var steps = _ecookbookContext.RecipeSteps.Where(Steps => Steps.RecipeId == id).ToList();

            foreach (var step in steps)
            {
                stepList.Add(step.Text);
            }


            var rating = _ecookbookContext.RecipeRating.Where(recipeRating => recipeRating.Recipe.Id == id)
                .ToList();

            var recipeRatingSum = 0;
            foreach (var rate in rating)
            {
                recipeRatingSum += rate.Rating;
            }

            var recipeRatingAvg = 0;
            if (rating.Count != 0)
            {
                recipeRatingAvg = recipeRatingSum / rating.Count;
            }

            var ingredientList = _ecookbookContext.RecipeIngredientses.Where(r => r.Recipes.Id == id).ToList();

            var ingredients = new List<string>();

            foreach (var ingredient in ingredientList)
            {
                var tmp = _ecookbookContext.Ingredients.Single(r => r.Id == ingredient.Id);
                ingredients.Add(tmp.Name);
            }

            var recipeDetails = new RecipeDetailsDTO
            {
                Title = recipe[0].Title, Id = recipe[0].Id, Comments = comments, Step = stepList,
                Rating = recipeRatingAvg, Ingredients = ingredients
            };


            ViewBag.recipe = recipeDetails;

            return View();
        }

        [Authorize]
        [HttpGet]
        [Route("addrecipe")]
        public async Task<IActionResult> AddRecipe()
        {
            var ingredients = await _ecookbookContext.Ingredients.ToListAsync();
            ViewBag.ingredients = ingredients;
            return View();
        }

        [Authorize]
        [HttpPost]
        [Route("addrecipe")]
        public async Task<IActionResult> AddRecipe([FromForm] Recipe recipe, ICollection<String>  RecipeIngredients, ICollection<String> RecipeSteps)
        {
/*            var ingredients = await _ecookbookContext.Ingredients.ToListAsync();
            ViewBag.ingredients = ingredients;*/

            var userId = _userManager.GetUserId(HttpContext.User);


            var userRecipe = new Recipe();


            var title = recipe.Title;
            var createdAt = new DateTime();
            createdAt = DateTime.Now;

            var recipeId = Guid.NewGuid().ToString();

            userRecipe.Id = recipeId;
            userRecipe.UserId = userId;

            userRecipe.Title = title;
            userRecipe.Createdat = createdAt;


            _ecookbookContext.Recipes.Add(userRecipe);

            foreach (var currentStep in RecipeSteps)
            {
                if (currentStep == null) continue;

                var recipeSteps = new RecipeStep();
                var guid = Guid.NewGuid().ToString();

                recipeSteps.Id = guid;
                recipeSteps.RecipeId = recipeId;
                recipeSteps.Text = currentStep;

                _ecookbookContext.RecipeSteps.Add(recipeSteps);
            }

            foreach (var ingredient in RecipeIngredients)
            {
                if (ingredient == null) continue;
                
                var recipeIngredients = new RecipeIngredient();
                var guid = Guid.NewGuid().ToString();

                recipeIngredients.Id = guid;
                recipeIngredients.RecipeId = recipeId;
                recipeIngredients.IngredientId = ingredient;

                _ecookbookContext.RecipeIngredientses.Add(recipeIngredients);
            }

            await _ecookbookContext.SaveChangesAsync();

            return RedirectToAction("Recipe", new {id = recipeId});
        }


        [Authorize]
        [HttpGet]
        [Route("addingredient")]
        public IActionResult AddIngredient()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        [Route("addingredient")]
        public async Task<IActionResult> AddIngredient([FromForm] Ingredient ingredient)
        {
            var _ingredient = _ecookbookContext.Ingredients.FirstOrDefault(i => i.Name == ingredient.Name);
            if (_ingredient == null)
            {
                ingredient.Id = Guid.NewGuid().ToString();
                await _ecookbookContext.Ingredients.AddAsync(ingredient);
                await _ecookbookContext.SaveChangesAsync();
                ViewBag.result = "Dodano składnik";
            }
            else
            {
                ViewBag.result = "Składnik już istnieje";
            }

            return View();
        }

        [Authorize]
        [HttpPost]
        [Route("addcomment")]
        public async Task<IActionResult> AddComment([FromForm] Comment comment, string returnUrl)
        {
            ViewData["ReturnUrl"] = returnUrl;
            return Redirect(returnUrl);
        }
    }
}

Views/Recipes/AddIngredient.cshtml
@model e_cookbook.Models.Ingredient

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}

<div class="container">
    <form asp-controller="Recipes" asp-action="AddIngredient">
          
        <h2>Dodaj składnik</h2>
            <div class="form-group">
                <label class="form-group" asp-for="Name">Nazwa składnika</label>
                <input class="form-group" type="text" placeholder="Nazwa" asp-for="Name"/>
            </div>
        <button type="submit" class="btn btn-primary float-right">Dodaj</button>
        
    </form>
    
    @ViewBag.result
</div>

Views/Recipes/AddRecipe.cshtml
@model e_cookbook.Models.Recipe

@{
    ViewBag.Title = "Nowy przepis";
    Layout = "_Layout";
}



@if(ViewBag.ingredients.Count == 0 )
{
    <h3>Nie ma żadnych składników!</h3>
    
}

<div class="bg-blur"></div>

<div class="login-form">
    <h3 class="m-md-2">Dodaj przepis</h3>
    <form asp-controller="Recipes" asp-action="addRecipe" class="form-recipe">
        <div class="form-group">
            <label asp-for="Title">Nazwa Przepisu</label>
            <input class="input-recipe" asp-controller="Recipes" asp-action="AddRecipe" asp-for="Title"/>
        </div>
        <div id="ingredients" class="form-group ">
            <label asp-for="RecipeIngredients">Dodaj artykuły</label><br/>
            @Html.DropDownList("accountid", new SelectList(ViewBag.ingredients, "Id", "Name"), new {@class = "col-md-7 form-control mr-1", @id = "select"})
            <i class="fa fa-plus-circle fa-lg add-ingredient"></i>
        </div>
        <div id="ingredients"></div>
        <div id="fields">

            <div class="newField form-group">
                <label asp-for="RecipeStep">Krok 1</label>
                <textarea onkeyup="textAreaAdjust(this)" class="step" asp-for="RecipeStep" name="RecipeSteps" id="input_1"> </textarea>
            </div>

        </div>
        <hr class="style13 add-hr"><i class="fa fa-plus-circle fa-lg add"></i>
        <button type="submit" class="btn btn-primary float-right">Dodaj</button>
    </form>

</div>

Views/Recipes/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<div class="MainPage" >

    <div class="row align-items-start">
        <div class="col-md-12" style="background: #333">
            <h2 style="text-align: center; color: #ffffff">Przepisy</h2>
        </div>
    </div>
    @model List<Ingredient>
    @if (ViewBag.recipes == null)
    {
        <div class="text-white;">
            <h1 class="text-center bg-dark text-white">Nie ma jeszcze żadnych przepisów!!</h1>
        </div>
    }
    else
    {
        foreach (var product in ViewBag.recipes)
        {
            <div class="row align-items-start">
                <div class="col-md-12">

                    <table class="table" style="text-align: center; border-collapse: collapse; width: 50%; color: #ffffff; font-weight: bold; margin: auto">

                        <tr>

                            <th style="text-align: center; padding: 8px; background-color: #003802; color: #ffffff;">@product.Title</th>

                        </tr>

                        <tr>
                            <th style="text-align: center; padding: 8px; background-color: #4CAF50; color: #ffffff;">Lista składników</th>


                        </tr>
                        <tr style="background-color: rgba(0, 0, 0, 0.3);">
                            <td style="text-align: center; padding: 8px;">
                                <ul style="display: inline-table;">
                                    @if (product.RecipeIngredients is null)
                                    {
                                        <li>Nie ma składników</li>
                                    }
                                    else
                                    {
                                        foreach (var i in product.Ingredients)
                                        {
                                            <li>@i.Name</li>
                                        }
                                    }



                                </ul>
                            </td>
                        </tr>

                        <tr>
                            <th style="text-align: center; padding: 8px; background-color: #4CAF50; color: #ffffff;">Lista kroków</th>

                        </tr>
                        <tr style="background-color: rgba(0, 0, 0, 0.3);">
                            <td style="text-align: center; padding: 8px;">
                                <ul style="display: inline-table;">
                                    @if (product.RecipeStep is null)
                                    {
                                        <li>Nie ma kroków</li>
                                    }
                                    else
                                    {
                                        foreach (var r in product.RecipeStep)
                                        {
                                            <li>@r.Text</li>
                                        }
                                    }
                                </ul>
                            </td>
                        </tr>
                    </table>
                    <br/>
                    <br/>
                </div>
            </div>
        }
    }
</div>

Views/Recipes/Recipe.cshtml
@model e_cookbook.Models.RecipeDetailsDTO

@{
    ViewBag.Title = "title";
    Layout = "_Layout";
}
<div class="container">
    <h2>Przepis: @ViewBag.recipe.Title</h2> <span>Rating: @ViewBag.recipe.Rating</span>


    @foreach (string ingredient in ViewBag.recipe.Ingredients)
    {
        <p>@ingredient</p>
    }

    @foreach (string step in ViewBag.recipe.Step)
    {
        <p>@step</p>
    }


    <form asp-controller="Recipes" asp-action="AddComment" asp-route-returnUrl="@ViewData["ReturnUrl"]">
        <h2>Komentarze</h2>
        <ul>
            @*         @foreach (string Comments in ViewBag.recipe.Comments) *@
            @*         { *@
            @*             foreach (var comment in Comments) *@
            @*             { *@
            @*               *@
            @*                 <li>@comment</li>    *@
            @*             } *@
            @*         } *@
        </ul>
        <button type="submit" class="btn btn-primary float-right">Dodaj komentarz</button>
    </form>
</div>